name: Optimize publish c4 to npm

on:
  workflow_dispatch:

jobs:
  publish-optimize-c4:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./optimize/c4
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: "Parse pom.xml for versions"
        id: "pom_info"
        uses: YunaBraska/java-info-action@main
        with:
          work-dir: ./optimize
      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: ${{ steps.pom_info.outputs.x_version_node }}
      - uses: camunda/infra-global-github-actions/setup-yarn-cache@main
        with:
          directory: optimize/c4
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" >> .npmrc
          npm publish --access=public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
