name: Update Identity Version
on:
  workflow_dispatch:
    inputs:
      identityVersion:
        description: 'The identity version to update to, for example 8.3.11'
        type: string
        required: true
      targetBranch:
        description: 'The branch to update the identity version on, typically a release branch like release-8.3.15'
        type: string
        required: true
      userSlackId:
        description: 'The slack id of the user to notify on failure, no mention within the alert message if omitted'
        type: string
        required: false
      dryRun:
        description: 'Whether to perform a dry run where no changes pushed, defaults to true'
        type: boolean
        default: true

jobs:
  update-identity:
    name: "Update the identity version to ${{ inputs.identityVersion }}"
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: checkout
        with:
          ref: ${{ inputs.targetBranch }}
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/zeebe/ci/zeebe ARTIFACTS_PSW;
            secret/data/products/zeebe/ci/zeebe ARTIFACTS_USR;
      - name: Git User Setup
        id: git-setup
        run: |
          git config --global user.email "github-actions[update-identity]"
          git config --global user.name "github-actions[update-identity]@users.noreply.github.com"
      - name: Get current identity version from `./parent/pom.xml`
        id: get-current-identity-version
        uses: mavrosxristoforos/get-xml-info@1.2.1
        with:
          xml-file: './parent/pom.xml'
          xpath: '//*[local-name()="version.identity"]'
      - name: Setup Zeebe Build Tooling
        uses: ./.github/actions/setup-build
        if: ${{ steps.get-current-identity-version.outputs.info != inputs.identityVersion }}
        with:
          camunda-nexus-username: ${{ steps.secrets.outputs.ARTIFACTS_USR }}
          camunda-nexus-password: ${{ steps.secrets.outputs.ARTIFACTS_PSW }}
          maven-cache-key-modifier: identity-update
      - name: Update identity version in ./parent/pom.xml
        id: update-identity-version
        if: ${{ steps.get-current-identity-version.outputs.info != inputs.identityVersion }}
        run: |
          ./mvnw versions:set-property -DgenerateBackupPoms=false -Dproperty=version.identity -DnewVersion=${{ inputs.identityVersion }} -pl parent
          git commit -am "deps(identity): update identity to ${{ inputs.identityVersion }}"
      - name: Push Changes to the target branch
        if: ${{ steps.update-identity-version.outcome == 'success' && inputs.dryRun == false }}
        run: git push origin "${{ inputs.targetBranch }}"
  notify:
    name: Send slack notification on failure
    runs-on: ubuntu-latest
    needs: [ update-identity ]
    if: ${{ failure() && inputs.dryRun == false }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    steps:
      - id: slack-notify-failure
        name: Send failure slack notification
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":alarm: *Updating the identity version* on `${{ inputs.targetBranch }}` failed! :alarm:\n ${{ inputs.userSlackId != '' && format('\\cc <@{0}>', inputs.userSlackId) || '' }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Please check the related workflow execution: https://github.com/camunda/camunda/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
