name: Zeebe Version Compatibility
on:
  workflow_dispatch:
  schedule:
    # Run at 6:00 every day
    - cron: '0 6 * * *'
concurrency:
  group: zeebe-version-compatibility
  cancel-in-progress: false

permissions:
  actions: read # Required to get the previous report

jobs:
  released-versions:
    name: Released Versions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shards: [ 1, 2, 3] # Values are not used, we just need an array of the right length
    steps:
      - uses: actions/checkout@v4
      - name: Find previous report
        id: get-last-run-id
        run: |
          runs=$(gh api /repos/camunda/zeebe/actions/workflows/zeebe-version-compatibility.yml/runs)
          last_run_id=$(echo $runs | jq 'first(.workflow_runs[] | select(.status=="completed").id)')
          echo "last_run_id=$last_run_id" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download previous report
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: zeebe-version-compatibility
          path: ${{ github.workspace }}
          run-id: ${{ steps.get-last-run-id.outputs.last_run_id }}
          github-token: ${{ github.token }}
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/zeebe/ci/zeebe ARTIFACTS_PSW;
            secret/data/products/zeebe/ci/zeebe ARTIFACTS_USR;
      - uses: ./.github/actions/setup-build
        with:
          camunda-nexus-username: ${{ steps.secrets.outputs.ARTIFACTS_USR }}
          camunda-nexus-password: ${{ steps.secrets.outputs.ARTIFACTS_PSW }}
      - uses: ./.github/actions/build-zeebe
        with:
          maven-extra-args: -PskipFrontendBuild
      - name: Test rolling update
        run: >
          ./mvnw -B --no-snapshot-updates -pl zeebe/qa/update-tests
          -D it.test=io.camunda.zeebe.test.RollingUpdateTest
          -D failsafe.rerunFailingTestsCount=3
          -D skipChecks
          verify
        env:
          ZEEBE_CI_CHECK_VERSION_COMPATIBILITY: true
          ZEEBE_CI_CHECK_VERSION_COMPATIBILITY_INDEX: ${{ strategy.job-index }}
          ZEEBE_CI_CHECK_VERSION_COMPATIBILITY_TOTAL: ${{ strategy.job-total }}
          ZEEBE_CI_CHECK_VERSION_COMPATIBILITY_REPORT: ${{ github.workspace }}/zeebe-version-compatibility
      - uses: ./.github/actions/collect-test-artifacts
        if: always()
        with:
          name: "Version compatibility ${{ strategy.job-index }}"
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zeebe-version-compatibility-${{ strategy.job-index }}
          path: ${{ github.workspace }}/zeebe-version-compatibility
  current-snapshot:
    name: Current Snapshot
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/zeebe/ci/zeebe ARTIFACTS_PSW;
            secret/data/products/zeebe/ci/zeebe ARTIFACTS_USR;
            secret/data/products/zeebe/ci/zeebe REGISTRY_HUB_DOCKER_COM_PSW_READ_ONLY;
            secret/data/products/zeebe/ci/zeebeREGISTRY_HUB_DOCKER_COM_USR;
      - uses: ./.github/actions/setup-build
        with:
          camunda-nexus-username: ${{ steps.secrets.outputs.ARTIFACTS_USR }}
          camunda-nexus-password: ${{ steps.secrets.outputs.ARTIFACTS_PSW }}
      - uses: ./.github/actions/build-zeebe
        with:
          maven-extra-args: -PskipFrontendBuild
      # Logging to DockerHub to to avoid being rate-limited when using an anonymous account from GitHub-managed runners.
      # jib-maven-plugin uses eclipse-temurin:xx image from DockerHub as base.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ steps.secrets.outputs.REGISTRY_HUB_DOCKER_COM_USR }}
          password: ${{ steps.secrets.outputs.REGISTRY_HUB_DOCKER_COM_PSW_READ_ONLY }}
      - uses: ./.github/actions/build-platform-docker
        with:
          version: current-test
      - name: Test snapshot
        run: >
          ./mvnw -B --no-snapshot-updates -pl zeebe/qa/update-tests
          -D it.test=io.camunda.zeebe.test.RollingUpdateTest
          -D failsafe.rerunFailingTestsCount=3
          -D skipChecks
          verify
        env:
          ZEEBE_CI_CHECK_CURRENT_VERSION_COMPATIBILITY: true
      - uses: ./.github/actions/collect-test-artifacts
        if: always()
        with:
          name: "Snapshot version compatibility"
  update-shared-report:
    name: Update Report
    runs-on: ubuntu-latest
    needs: released-versions
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Download all reports
        uses: actions/download-artifact@v4
        with:
          pattern: zeebe-version-compatibility-*
      - name: Merge reports
        run : |
          cat zeebe-version-compatibility-*/** | sort | uniq > ${{ github.workspace }}/zeebe-version-compatibility
          if [ ! -s ${{ github.workspace }}/zeebe-version-compatibility ]; then
            exit 1
          fi
      - name: Upload shared report
        uses: actions/upload-artifact@v4
        with:
          name: zeebe-version-compatibility
          path: ${{ github.workspace }}/zeebe-version-compatibility
  notify:
    name: Notify on failure
    runs-on: ubuntu-latest
    needs: [released-versions, current-snapshot]
    if: failure()
    steps:
      - uses: actions/checkout@v4
      - id: slack-notify
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":warning: *Zeebe Version Compatibility checks failed:*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Please check the related workflow execution: https://github.com/camunda/camunda/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
